;; This "manifest" file can be passed to 'guix package -m' to reproduce
;; the content of your profile.  This is "symbolic": it only specifies
;; package names.  To reproduce the exact same profile, you also need to
;; capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(specifications->manifest
  (list "gash"
        "ed"
        "parallel"
        "nushell"
        "es"
        "rc"
        "mosh"
        "rush"
        "s-shell"
        "scsh"
        "vim"
        "emacs"
        "zsh-autosuggestions"
        "zsh-syntax-highlighting"
        "shellcheck"
        "oil"
        "loksh"
        "mksh"
        "oksh"
        "fish"
        "tcsh"
        "zsh"
        "dash"
        "xonsh"
        "glances"
        "git"
        "imagemagick"
        "ffmpeg"
        "mtr"
        "rsync"
        "screen"
        "curl"
        "tmux"
        "htop"
        "nmap"
        "youtube-dl"
        "lolcat"
        "cowsay"
        "cmatrix"
        "neofetch"
        "feh"
        "ncdu"
        "ranger"))
